export const LIST_SONGS_CHANGE = 'LIST_SONGS_CHANGE';
export const TOGGLE_PLAY_PAUSE = 'TOGGLE_PLAY_PAUSE';
export const VOLUME_CHANGE = 'VOLUME_CHANGE';
export const CURRENT_TIME_CHANGE = 'CURRENT_TIME_CHANGE';
export const SEEK_TIME = 'SEEK_TIME';
export const THEME_TOGGLE = 'THEME_TOGGLE';
export const SERVER_ERROR = 'SERVER_ERROR';



